# Site settings
title: Victor Hugo de Paiva Gonçales - victorvhpg
email: victorvhpg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Victor Hugo de Paiva Gonçales - victorvhpg
baseurl: ""
url: "https://victorvhpg.github.io"
twitter_username: victorvhpg
github_username:  victorvhpg
# Build settings
markdown: kramdown
exclude: [assets/conteudo-posts/2018/redux/conta-bancaria/node_modules]
